import 'dart:io';
import 'dart:math';

/*
1. Print out a 3x3 matrix of dots
2. Ask the user for a (x,y) coordinate of their mark (O)
3. Reprint the 3x3 matrix with an update for the user's mark
4. Reprint the matrix with the robot's mark (x)
5. Repeat...
6. When a line of same the same marks is formed, end the game
*/

void matrix_print(List a){
	print('''
			${a[2][0]}	${a[2][1]}	${a[2][2]}

			${a[1][0]}	${a[1][1]}	${a[1][2]}

			${a[0][0]}	${a[0][1]}	${a[0][2]}
			''');
}

void check_win(List a){

	// Horizontal win: check each row for equal chars
	for(int row = 0; row <= 2; row++){
		if (a[row][0] == a[row][1] && a[row][0] == a[row][2]){
			if (a[row][0] == 'X'){
				print('!!! You WON !!!');
				exit(0);
			}else if(a[row][0] == 'O'){
				print('!!! I WON... lol!!!');
				exit(0);
			}
		}
	}

	// Vertical win: check each column
	for(int col = 0; col <= 2; col++){
		if (a[0][col] == a[1][col] && a[1][col] == a[2][col]){
			if (a[0][col] == 'X'){
				print('!!! You WON !!!');
				exit(0);
			}else if(a[0][col] == 'O'){
				print('!!! I WON... lol!!!');
				exit(0);
			}
		}
	}


	// Diagonal (right) win
	if (a[0][0] == a[1][1] && a[1][1] == a[2][2]){
		if (a[0][0] == 'X'){
			print('!!! You WON !!!');
			exit(0);
		}else if(a[0][0] == 'O'){
			print('!!! I WON... lol!!!');
			exit(0);

		};
	}

	if (a[0][2] == a[1][1] && a[1][1] == a[2][0]){
		if (a[0][2] == 'X'){
			print('!!! You WON !!!');
			exit(0);
		}else if(a[0][2] == 'O'){
			print('!!! I WON... lol!!!');
			exit(0);

		};
	}
}

void main(){
	List matrix = [
		['.', '.', '.'],
		['.', '.', '.'],
		['.', '.', '.']];
	print('Let\'s start the game!!!');
	matrix_print(matrix);
	
	for(int i = 0; i <= 9; i++){
		stdout.write('Enter the coordinates of your mark [x,y]: ');
		List <int> points = [];
		// addAll elements of the integer iterable (to points) generated by mapping parse() to each elem of the string list (point)
		points.addAll(((stdin.readLineSync() ?? '1,1').split(',')).map((x) => int.parse(x)));

		matrix[points[0]][points[1]] = 'X';
		matrix_print(matrix);
		check_win(matrix);
		stdout.write('I\'m playing my move...');

		int comp_x;
		int comp_y;

		do{
			//Random rand = new Random();
			comp_x = Random().nextInt(3);
			comp_y = Random().nextInt(3);
		}while (matrix[comp_x][comp_y] == 'X' || matrix[comp_x][comp_y] == 'O');

		sleep(Duration(seconds:1));
		print('Here:');

		matrix[comp_x][comp_y] = 'O';
		matrix_print(matrix);
		check_win(matrix);
		print('Your chance now...');
	}
}
